export class CommonConstants {
  static readonly COLOR_BG = '#FAFAF9';
  static readonly COLOR_CARD = '#FFFFFF';
  static readonly COLOR_PRIMARY = '#333333';
  static readonly COLOR_SECONDARY = '#8E8E93';
  
  static readonly PAGE_PADDING = 24;
  
  // Page URLs / Keys
  static readonly URL_HOME = 'HomePage';
  static readonly URL_EDITOR = 'MoodEditorPage';
  static readonly URL_TOOLS = 'ToolsPage';
  static readonly URL_STATS = 'StatsPage';
  static readonly URL_SETTINGS = 'SettingsPage';
}
